# Generated by Django 4.2.10 on 2024-02-20 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes_app', '0002_rename_is_delete_notesuser_can_delete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='note_creator', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notes',
            name='modified_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='note_modifier', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
