# Generated by Django 4.2.10 on 2024-02-21 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes_app', '0003_notes_created_by_notes_modified_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotesAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('old_note_content', models.TextField()),
                ('new_note_content', models.TextField()),
                ('old_note_type', models.CharField(max_length=20)),
                ('new_note_type', models.CharField(max_length=20)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('notes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_audit', to='notes_app.notes')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
