# Generated by Django 4.2.10 on 2024-02-21 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0004_notesaudit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notesaudit',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
